CREATE TABLE IF NOT EXISTS notices (
  id         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  title      VARCHAR(120) NOT NULL,
  content    TEXT NOT NULL,
  image_url  VARCHAR(255) NULL,
  pinned     BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_notices_pinned_created_at (pinned, created_at)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE notices ADD COLUMN IF NOT EXISTS image_url VARCHAR(255) NULL;
ALTER TABLE notices DROP COLUMN IF EXISTS image_data;
